// This file is auto-generated by scripts/set-env.js
// Do not edit this file directly. Edit .env or set environment variables instead.

export const environment = {
    production: false,
    apiUrl: 'http://localhost:8080/api',
    nodeEnv: 'development'
};
