// This file is auto-generated from .env
// Do not edit this file directly. Edit .env instead.

export const environment = {
    production: false,
    apiUrl: 'http://localhost:8080/api',
    nodeEnv: 'development'
};
