/**
 * Script to generate environment files from environment variables
 * This runs before the Angular build process
 *
 * Usage: node scripts/set-env.js
 */

const { writeFileSync, mkdirSync, existsSync } = require('fs');
const { join } = require('path');
require('dotenv').config();

const environmentsDir = join(__dirname, '..', 'src', 'environments');

// Ensure environments directory exists
if (!existsSync(environmentsDir)) {
    mkdirSync(environmentsDir, { recursive: true });
}

// Determine if this is a production build
const isProduction = process.env.NODE_ENV === 'production' ||
    process.env.VERCEL_ENV === 'production' ||
    process.env.NG_APP_NODE_ENV === 'production';

// Read environment variables with fallbacks
const apiUrl = process.env.NG_APP_API_URL || 'http://localhost:8080/api';
const nodeEnv = isProduction ? 'production' : 'development';

const environmentFileContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit this file directly. Edit .env or set environment variables instead.

export const environment = {
    production: ${isProduction},
    apiUrl: '${apiUrl}',
    nodeEnv: '${nodeEnv}'
};
`;

// Write to environment.ts
const envFilePath = join(environmentsDir, 'environment.ts');
writeFileSync(envFilePath, environmentFileContent);
console.log('Generated ' + envFilePath);
console.log('   - production: ' + isProduction);
console.log('   - apiUrl: ' + apiUrl);
console.log('   - nodeEnv: ' + nodeEnv);
